### ISSUE TITLE
Add a golang implementation.

### ISSUE THREAD

**Issue by brendandburns** [metaparticle-io/sync#2]

**Comment by nicholasjackson** [comment]
Hi @brendanburns, Nic here from HashiCorp, this looks super interesting would love to help out in my spare time.

**Comment by brendandburns** [comment]
@nicholasjackson sorry for the delay, but it would be great to get a golang impl here...

**Comment by nicholasjackson** [comment]
@brendandburns cool, double delay, too many GitHub notifications, I will take a quick look this weekend
